config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  namespace :admin do
    resources :players, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'teamtop', to: 'teams#index'
  
  resources :users, only: [:show, :new, :create, :edit, :update]

  resources :teams

  resources :players, only: [:show, :index]
  resources :favorites, only: [:create, :destroy]
  resources :members, only: [:create, :update]
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  validates :sex, presence: true,
      numericality: { only_integer: true, greater_than: 0, lesser_than: 2, allow_blank: true }
      
  validates :birthday, presence: true
    
  has_secure_password
  
  has_many :favorites
  has_many :favorite_players, through: :favorites, source: :player
  has_many :teams, dependent: :destroy

  def add_favorite(player)
    self.favorites.find_or_create_by(player_id: player.id)
  end

  def remove_favorite(player)
    favorite = self.favorites.find_by(player_id: player.id)
    favorite.destroy if favorite
  end
  
  def is_favarite_player?(player)
    self.favorite_players.include?(player)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show, :edit, :update]
  
  def show
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(safe_user_params)
    if @user.save
      flash[:success] = '登録しました'
      redirect_to root_url
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end

  def destroy
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(safe_user_params)
      flash[:success] = 'アカウントを更新しました'
      redirect_to @user
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end
  
  private
  
  def safe_user_params
    params.require(:user).permit(:name, :email, :sex, :birthday, :password, :password_confirmation)
  end
  
  def require_user
    if current_user.id != params[:id].to_i
      redirect_to root_url
    end
  end
  
end

app/views/users/_user_profile.html.erb
<div class="col-sm-6 offset-sm-3">
    
    <%= form_with(model: user, local: true) do |f| %>
        <%= render 'layouts/error_user_messages' %>
        <div class="form-group">
            <%= f.label :name, 'Name' %>
            <%= f.text_field :name, class: 'form-control' %>
        </div>
        
        <div class="form-group">
            <%= f.label :email, 'Email' %>
            <%= f.email_field :email, class: 'form-control' %>
        </div>

         <div class="form-group">
            <%= f.radio_button :sex, 1, checked: true %>
            <%= f.label :sex, "男" %>
            <%= f.radio_button :sex, 2 %> 
            <%= f.label :sex, "女" %>
        </div>
        
        <div class="form-group">
            <%= f.label :birthday, "Birthday" %>
            <%= f.date_select :birthday, start_year: 1940, end_year: Time.current.year, use_month_numbers: true %>
        </div>

        <div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'form-control' %>
        </div>

        <div class="form-group">
            <%= f.label :password_confirmation, 'Password Confirmation' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        
      <%= f.submit action, class: 'btn btn-primary btn-block' %>
    <% end %>
    
</div>

app/views/users/edit.html.erb
<div class="row">
    <h1 class="col-sm-12 text-center">アカウント設定</h1>
</div>

<div class="row">
    <%= render "user_profile", user: @user, action: '更新' %>
</div>

app/views/users/new.html.erb
<div class="row">
    <h1 class="col-sm-12 text-center">アカウント登録</h1>
</div>

<div class="row">
    <%= render "user_profile", user: @user, action: '登録' %>
</div>

app/views/users/show.html.erb
<div class="container">
    <h2><%= current_user.name %>さんの設定</h2>
    
    <div class="row mt-5">
        <h3 class="col-md-3">マイチーム一覧</h2>
        <div class="col-md-3">
            <%= link_to '新チームをつくる', new_team_path, class: 'btn btn-primary btn-block btn-sm' %>
        </div>
    </div>

    <%= render 'teams/teams_list', teams: current_user.teams %>

    <div class="row mt-5">
        <h3>お気に入り選手一覧</h2>
        <%= render 'players/players_list', players: current_user.favorite_players %>
    </div>

    <div class="offset-4 col-md-4">
        <%= link_to 'アカウント設定', edit_user_path(current_user) , class: 'btn btn-primary btn-block' %>
    </div>
    
    <% if current_user&.administrator? %>
        <div class="row mt-5 offset-4 col-md-4">
            <%= link_to '新規選手登録', new_admin_player_path , class: 'btn btn-primary btn-block' %>
        </div>
    <% end %>    
    
</div>