config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'

  namespace :admin do
    resources :players, only: [:new, :create, :edit, :update, :destroy]
  end

  get 'signup', to: 'users#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'teamtop', to: 'teams#index'
  
  resources :users, only: [:show, :new, :create, :edit, :update]

  resources :teams

  resources :players, only: [:show, :index]
  resources :favorites, only: [:create, :destroy]
  resources :members, only: [:create, :update]
end

app/models/player.rb
class Player < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  validates :name, presence: true, uniqueness: true, length: { maximum: 40 }
  validates :position, presence: true, inclusion: { in: %w(PR HO LO FL NO8 SH SO CTB WTB FB UTB)}
  validates :height, presence: true, numericality: { only_integer: true }
  validates :weight, presence: true, numericality: { only_integer: true }
  validates :birthday, presence: true
  # validates :country, presence: true
  # validates :image, format { with: \.[jpeg png] }
  
  has_many :favorites
  has_many :followers, through: :favorites, source: :user
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < Admin::Base

  def new
    @player = Player.new
    # render 'admin/players/new'
  end
  
  def create
    @player = Player.new(safe_player_params)
    if @player.save
      flash[:success] = '選手登録しました'
      redirect_to @player
    else
      flash.now[:danger] = '選手登録に失敗しました'
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(safe_player_params)
      flash[:success] = '更新しました'
      redirect_to edit_admin_player_url(@player)
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end
  
  private
  
  def safe_player_params
    params.require(:player).permit(:name, :height, :weight, :position, :birthday, :country_code, :image)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    #return @players if not params[:positon]
    
    if params[:search].blank? && ( params[:position].blank? || params[:position] == 'ALL' )
      return @players =  Player.order(id: :desc).page(params[:page]).per(10)
    end

    # search rugby player with 'name' and 'position'
    # improve searching part of name 
    if params[:position] == 'ALL'
      @players = Player.where(name: params[:search])
    elsif params[:search].blank?
      @players = Player.where(position: params[:position])
    else
      @players = Player.where(name: params[:search], position: params[:position])
    end
    
    @players = @players.order(id: :desc).page(params[:page]).per(10)
  end

  def show
    @player = Player.find(params[:id])
  end

  private
  
  def safe_player_params
    params.require(:player).permit(:name, :height, :weight, :position, :birthday, :country_code, :image)
  end
end

app/helpers/players_helper.rb
module PlayersHelper
  POSITIONS =  ['PR', 'HO', 'LO', 'FL', 'NO8', 'SH', 'SO', 'CTB', 'WTB', 'FB', 'UTB']
end

app/views/players/_player_profile.html.erb
<aside class="col-sm-3">
    <%  if player.image? %>
        <%= image_tag player.image.url, :size =>'200x200' %>
    <% else %>
        <p class="text-center">登録画像なし</p>
        <%= image_tag ('ruger_man.png'), alt: "rugby player image" %>
    <% end %>
</aside>
<div class="col-sm-6">
    <% if action %>
        <%= form_with(model: player, local: true) do |f| %>
            <table class="table table-striped table-bordered table-sm">
                <tr>
                    <th><%= f.label :name, 'Name' %></th>
                    <td><%= f.text_field :name, class: 'form-control' %></td>
                </tr>
        
                <tr>
                   <th><%= f.label :height, 'Height[cm]' %></th> 
                   <td><%= f.text_field :height, class: 'form-control' %></td>
                </tr>
        
                <tr>
                    <th><%= f.label :weight, 'Weight[kg]' %></th>
                    <td><%= f.text_field :weight, class: 'form-control' %></td>
                </tr>
        
                <tr>
                    <th><%= f.label :position, 'Position' %></th>
                    <td><%= f.select :position, PlayersHelper::POSITIONS, class: 'form-control' %></td>
                </tr>
                
                <tr>
                    <th><%= f.label :birthday, "Birthday" %></th>
                    <td><%= f.date_select :birthday, start_year: 1960, end_year: Time.current.year, use_month_numbers: true %></td>
                </tr>
                
                <tr>
                    <th><%= f.label :country, "Country from"%></th>
                    <td><%= f.country_select :country_code %></td>
                </tr>
                
                <tr>
                    <th><%= f.label :image, "画像" %></th>
                    <td><%= f.file_field :image %></td>
                </tr>

                
            </table>
            <%= f.submit action, class: 'btn btn-primary btn-block' %>
        <% end %>
    <% else %>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th>Name</th>
                <td><%= player.name %></td>
            </tr>
    
            <tr>
               <th>Height[cm]</th> 
               <td><%= player.height %></td>
            </tr>
    
            <tr>
                <th>Weight[kg]</th>
                <td><%= player.weight %></td>
            </tr>
    
            <tr>
                <th>Position</th>
                <td><%= player.position %></td>
            </tr>
            
            <tr>
                <th>Birthday</th>
                <td><%= player.birthday %></td>
            </tr>
            
            <tr>
                <th>Country from</th>
                <td><%= player.country_code %></td>
            </tr>
            
        </table>    
    <% end %>
    
</div>

app/views/players/index.html.erb
<h1>選手一覧</h1>
<% if logged_in? %>
  <p class="text-danger">お気に入りした選手は自分のチームに登録できます</p>
<% end %>
<%= form_tag players_path, :method => 'get' do %>
  <p>
      <%= text_field_tag :search, params[:search] %>
      <%= select_tag :position, options_for_select( %w(ALL PR HO LO FL NO8 SH SO CTB WTB FB UTB)) %>
      <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>
<%= render 'players_list', players: @players %>
<%= paginate @players %>

app/views/players/new.html.erb
<div class="text-center">
    <h1>選手登録</h1>
</div>

<div class="row">
    <%= render 'player_profile', player: @player, action: '登録' %>
</div>

app/views/players/show.html.erb
<div class="text-center m-5">
    <h1>選手プロフィール</h1>
</div>

<div class="row">
    <%= render 'player_profile', player: @player, action: nil %>
</div>
<div class="row">
    <div class="offset-3 col-md-2">
        <%= link_to '変更', [:edit, :admin, @player], class: 'btn btn-primary btn-block' if current_user&.administrator? %>
    </div>
</div>